# Generated by Django 6.0 on 2026-08-25 20:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Informe o código do projeto', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Código do Projeto')),
                ('nome', models.CharField(help_text='Informe o nome do projeto', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome do Projeto')),
                ('tipo_projeto', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('LIBRARY', 'Library'), ('DATA_SCIENCE', 'Data Science'), ('AI', 'Inteligência Artificial')], help_text='Informe o tipo do projeto', max_length=20, verbose_name='Tipo do Projeto')),
                ('cliente', models.CharField(help_text='Informe o nome do cliente', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cliente')),
                ('gerente', models.CharField(help_text='Informe o nome do gerente', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Gerente')),
                ('inicio', models.DateField(help_text='Informe a data de início do projeto', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Início')),
                ('previsao_termino', models.DateField(help_text='Informe a data de previsão de término do projeto', verbose_name='Previsão de Término')),
                ('fim', models.DateField(blank=True, help_text='Informe a data real de término do projeto', null=True, verbose_name='Data de Fim')),
                ('orcamento', models.DecimalField(decimal_places=2, help_text='Informe o orçamento do projeto', max_digits=10, verbose_name='Orçamento')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Informe o título da tarefa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(blank=True, help_text='Informe a descrição da tarefa', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Descrição da Tarefa')),
                ('linguagem', models.CharField(choices=[('PYTHON', 'Python'), ('JS', 'JavaScript'), ('JAVA', 'Java'), ('CSHARP', 'C#'), ('CPLUSP', 'C++'), ('C', 'C'), ('PHP', 'PHP'), ('DART', 'Dart')], help_text='Informe a linguagem da tarefa', max_length=50, verbose_name='Linguagem da Tarefa')),
                ('estimativa_horas', models.PositiveIntegerField(help_text='Informe a estimativa de horas da tarefa', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Estimativa de Horas da Tarefa')),
                ('horas_registradas', models.PositiveIntegerField(blank=True, help_text='Informe as horas registradas da tarefa', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Registradas da Tarefa')),
                ('prioridade', models.PositiveIntegerField(blank=True, help_text='Informe a prioridade da tarefa', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade da Tarefa')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DOING', 'Em andamento'), ('DONE', 'Concluída'), ('BLOCKED', 'Bloqueada'), ('DELAYED', 'Atrasada')], help_text='Informe o status da tarefa', max_length=20, verbose_name='Status da Tarefa')),
                ('responsavel', models.CharField(help_text='Informe o responsável pela tarefa', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Responsável pela Tarefa')),
                ('criacao', models.DateField(help_text='Informe a data de criação da tarefa', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Criação da Tarefa')),
                ('conclusao', models.DateField(blank=True, help_text='Informe a data de conclusão da tarefa', null=True, verbose_name='Data de Conclusão da Tarefa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gestao.projeto', verbose_name='Projeto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
