# Generated by Django 6.0 on 2026-08-25 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='conclusao',
            field=models.DateTimeField(blank=True, help_text='Informe a data e hora de conclusão da tarefa', null=True, verbose_name='Data de Conclusão da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='criacao',
            field=models.DateTimeField(help_text='Informe a data e hora de criação da tarefa', verbose_name='Data de Criação da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Informe a descrição da tarefa', max_length=1000, null=True, verbose_name='Descrição da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='estimativa_horas',
            field=models.PositiveIntegerField(help_text='Informe a estimativa de horas da tarefa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimativa de Horas da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='horas_registradas',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Informe as horas registradas da tarefa', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Registradas da Tarefa'),
        ),
    ]
