# Generated by Django 6.0 on 2026-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_tarefa_conclusao_alter_tarefa_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='inicio',
            field=models.DateField(help_text='Informe a data de início do projeto', verbose_name='Data de Início'),
        ),
    ]
